import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./components/auth/AuthContext";
import TopBar from "./components/topbar/Topbar";
import Sidebar from "./components/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  showNav?: boolean;
}

export default function RootLayout({
  children,
  showNav = true 
}: RootLayoutProps) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex h-screen bg-gray-100">
            {showNav && <Sidebar />}
            <div className="flex flex-col flex-grow">
              {showNav && <TopBar />}
              <main className="flex-grow p-4">
                {children}
              </main>
            </div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
